export const MCP_DESCRIPTION_ZH = {
    playwright: "模拟浏览器行为，用于网页导航、数据抓取和自动化网页交互。",
    filesystem: "支持文件和目录的读取、写入、删除、重命名、移动以及列表查看等操作。",
    "chrome-mcp-server": "控制 Chrome 执行各种交互式操作。",
    "mcp-server-commands": "通过后端服务执行本地系统命令。",
    mysql: "管理 MySQL 服务。",
    binance: "获取 Binance 的加密货币信息。",
    github: "基于 GitHub API 管理 GitHub。",
    fetch: "抓取网页内容。",
    amap: "从高德地图服务获取地理信息。",
    "bocha-search": "使用博查 AI 搜索全网信息，返回更适合 AI 使用的网页结果与摘要。",
    "mcp-server-alipay": "调用支付宝支付 API。",
    wuying: "调用 AI Agent 云服务 API。",
    "sequential-thinking": "通过顺序推理，以逐步且合乎逻辑的方式分析问题或任务。",
    xiyan: "支持用自然语言查询数据库。",
    "baidu-map": "从百度地图服务获取地理信息。",
    oceanbase: "管理 OceanBase。",
    minimax: "调用强大的文本转语音以及视频、图像生成 API。",
    edgeone: "将 HTML 内容、文件夹或 ZIP 包部署到 EdgeOne Pages，并获取可公开访问的 URL。",
    time: "处理时间相关功能。",
    gitlab: "基于 GitLab API 管理 GitLab。",
    flomo: "向 Flomo 写入笔记。",
    firecrawl: "通过 Firecrawl 的网页抓取能力，为 AI Agent 从任意网站提取数据。",
    perplexity: "让 AI 工具通过 Perplexity 强大的搜索引擎进行实时全网研究。",
    exa: "让 AI 助手通过 Exa AI Search API 执行网页搜索。",
    figma: "通过该 MCP 服务访问你的 Figma 文件。",
    blender: "允许 AI 直接与 Blender 交互并进行控制。",
    slack: "获取 Slack 私聊、群聊和历史消息。",
    AbletonMCP: "允许 AI 直接与 Ableton Live 交互并进行控制。",
    redis: "为 Redis 提供自然语言接口，便于 Agent 高效管理和搜索数据。",
    browserbase: "让 LLM 应用能够无缝接入外部数据源和工具的 MCP 服务。",
    magic: "通过自然语言描述，帮助开发者快速生成美观、现代的 UI 组件。",
    everything: "用于演示 MCP 协议全部特性的测试服务，包含 prompts、tools、resources、sampling 等能力。",
    gdrive: "集成 Google Drive，可列出、读取、搜索文件，并支持读写 Google Sheets。",
    memory: "基于本地知识图谱实现持久化记忆，让 AI 能跨聊天记住用户信息。",
    "brave-search": "集成 Brave Search API，提供网页搜索、本地兴趣点、图片、视频和新闻搜索。",
    sentry: "以安全方式将 Sentry 的完整问题上下文引入系统中。",
    "google-maps": "通过环境变量中的 API Key 访问 Google 地图服务。",
    puppeteer: "通过 Puppeteer 驱动浏览器自动化和网页交互。",
    chatsum: "总结聊天消息内容。",
    everart: "集成 EverArt 的 AI 模型，生成矢量和位图图像。",
    arxiv: "在 AI 助手与 arXiv 研究论文仓库之间建立桥梁。",
    idb: "集成 MCP 与 Facebook 的 idb（iOS Development Bridge），支持自动化 iOS 设备管理。",
    graphlit: "让 MCP 客户端与 Graphlit 服务集成。",
    xhs: "基于 AI 管理小红书（RedNote）。",
    "awslabs.core-mcp-server": "作为 MCP 框架的核心组件，为其他 AWS 相关 MCP 服务提供基础能力和通用支持。",
    "awslabs.nova-canvas-mcp-server": "结合 AWS 的 AI 与机器学习能力，集成 Amazon Nova Canvas，用于画布相关交互和生成式 AI 处理。",
    "awslabs.bedrock-kb-retrieval-mcp-server": "深度集成 Amazon Bedrock Knowledge Base Retrieval，让模型检索 Bedrock 知识库中的信息。",
    "awslabs.aws-pricing-mcp-server": "提供实时 AWS 服务价格信息，便于查询和理解各项服务成本。",
    "awslabs.cdk-mcp-server": "与 AWS CDK 紧密结合，帮助模型理解、生成或辅助编写 AWS 的基础设施即代码。",
    "awslabs.aws-documentation-mcp-server": "实时访问 AWS 官方文档，帮助模型获取最新服务信息、技术指南和最佳实践，降低幻觉。",
    "awslabs.lambda-tool-mcp-server": "集成 AWS Lambda 工具能力，帮助模型管理、部署或调用 Lambda 函数。",
    "awslabs.terraform-mcp-server": "与 Terraform 紧密集成，帮助模型理解、生成或管理基于 Terraform 的 AWS 资源部署。",
    "awslabs.frontend-mcp-server": "聚焦前端开发工具与支持，为模型提供 AWS 云内前端技术、框架和部署流程相关能力。",
    "awslabs.valkey-mcp-server": "集成 AWS MemoryDB for Valkey，让模型能够查询或操作 Valkey 数据库。",
    "awslabs.aws-location-mcp-server": "提供 AWS Location 服务访问能力，支持处理地理空间数据、地图及位置服务场景。",
    "awslabs.memcached-mcp-server": "集成 AWS ElastiCache for Memcached，让模型与高性能缓存系统交互。",
    "awslabs.git-repo-research-mcp-server": "聚焦 Git 仓库研究，帮助模型分析 GitHub 等平台上的代码仓库、提取信息或辅助代码评审。",
    "awslabs.cloudformation": "集成 AWS CloudFormation，帮助模型理解、生成或辅助使用模板来定义和部署云资源栈。",
};

export function getMcpDescription(name, englishDescription, language = "zh") {
    if (language === "en") {
        return englishDescription || "-";
    }

    return MCP_DESCRIPTION_ZH[name] || englishDescription || "-";
}
